[package]
name = "dll-proxy-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
windows-sys = { version = "0.60.2", features = ["Win32_System_LibraryLoader"] }
